# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

GOOGLE_API_SERVER_KEY: "AIzaSyAGO-SnCOW9q9Eg47eaNn4KwOhoMpwSTdc"
GOOGLE_API_BROWSER_KEY: "AIzaSyBHqi9MEqrP2ncl7qD4bSm5sVIAhzPY-TE"

DEVISE_SECRET_KEY: "a7eb7e450eb4e10a77f12550b832f60362b3c78a8d5b471456f893d77e7e1928bf6b40ecafbef61583ecea8df17983691add4f9dca50de0c6e25d448c2f7ffe8"
GMAIL_PSW: "11Mai1988"
